package:
  name: chemview
  version: !!str 0.7

source:
   path: ../
#  git_url: https://github.com/gabrielelanaro/chemview.git
#  git_tag: v0.7

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - jupyter

  run:
    - python
    - matplotlib
    - ipywidgets
    - numba
    - numpy
    - jupyter
    - notebook

test:
  imports:
    - chemview

about:
  home: http://chemview.rtfd.org
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: WebGL Molecular Viewer for Jupyter notebook.
